FROM bellsoft/liberica-openjdk-alpine:17
WORKDIR usr/src
ADD ./target/recommended-service-0.0.1-SNAPSHOT.jar /usr/src/recommended-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","recommended-service-0.0.1-SNAPSHOT.jar"]